from flask import Flask, render_template, request, jsonify

app = Flask(__name__)

# 원소 데이터
elements={
    "H":{"name":"수소", "atomic_number":1, "atomic_weight":1.008, "period":1, "group":1, "electronegativity": 2.2},
    "He":{"name":"헬륨", "atomic_number":2, "atomic_weight":4.0026, "period":1, "group":18, "electronegativity": None},
    "Li": {"name": "리튬", "atomic_number": 3, "atomic_weight": 6.94, "period": 2, "group": 1, "electronegativity": 0.98},
    "Be": {"name": "베릴륨", "atomic_number": 4, "atomic_weight": 9.0122, "period": 2, "group": 2, "electronegativity": 1.57},
    "B": {"name": "붕소", "atomic_number": 5, "atomic_weight": 10.81, "period": 2, "group": 13, "electronegativity": 2.04},
    "C": {"name": "탄소", "atomic_number": 6, "atomic_weight": 12.011, "period": 2, "group": 14, "electronegativity": 2.55},
    "N": {"name": "질소", "atomic_number": 7, "atomic_weight": 14.007, "period": 2, "group": 15, "electronegativity": 3.04},
    "O": {"name": "산소", "atomic_number": 8, "atomic_weight": 15.999, "period": 2, "group": 16, "electronegativity": 3.44},
    "F": {"name": "플루오린", "atomic_number": 9, "atomic_weight": 18.998, "period": 2, "group": 17, "electronegativity": 4.0},
    "Ne": {"name": "네온", "atomic_number": 10, "atomic_weight": 20.180, "period": 2, "group": 18, "electronegativity": None},
    "Na": {"name": "나트륨", "atomic_number": 11, "atomic_weight": 22.990, "period": 3, "group": 1, "electronegativity": 0.93},
    "Mg": {"name": "마그네슘", "atomic_number": 12, "atomic_weight": 24.305, "period": 3, "group": 2, "electronegativity": 1.31},
    "Al": {"name": "알루미늄", "atomic_number": 13, "atomic_weight": 26.982, "period": 3, "group": 13, "electronegativity": 1.61},
    "Si": {"name": "규소", "atomic_number": 14, "atomic_weight": 28.085, "period": 3, "group": 14, "electronegativity": 1.9},
    "P": {"name": "인", "atomic_number": 15, "atomic_weight": 30.974, "period": 3, "group": 15, "electronegativity": 2.19},
    "S": {"name": "황", "atomic_number": 16, "atomic_weight": 32.06, "period": 3, "group": 16, "electronegativity": 2.58},
    "Cl": {"name": "염소", "atomic_number": 17, "atomic_weight": 35.45, "period": 3, "group": 17, "electronegativity": 3.16},
    "Ar": {"name": "아르곤", "atomic_number": 18, "atomic_weight": 39.948, "period": 3, "group": 18, "electronegativity": None},
    "K": {"name": "칼륨", "atomic_number": 19, "atomic_weight": 39.098, "period": 4, "group": 1, "electronegativity": 0.82},
    "Ca": {"name": "칼슘", "atomic_number": 20, "atomic_weight": 40.078, "period": 4, "group": 2, "electronegativity": 1.0},
    "Sc": {"name": "스칸듐", "atomic_number": 21, "atomic_weight": 44.956, "period": 4, "group": 3, "electronegativity": 1.36},
    "Ti": {"name": "티타늄", "atomic_number": 22, "atomic_weight": 47.867, "period": 4, "group": 4, "electronegativity": 1.54},
    "V": {"name": "바나듐", "atomic_number": 23, "atomic_weight": 50.942, "period": 4, "group": 5, "electronegativity": 1.63},
    "Cr": {"name": "크로뮴", "atomic_number": 24, "atomic_weight": 51.996, "period": 4, "group": 6, "electronegativity": 1.66},
    "Mn": {"name": "망가니즈", "atomic_number": 25, "atomic_weight": 54.938, "period": 4, "group": 7, "electronegativity": 1.55},
    "Fe": {"name": "철", "atomic_number": 26, "atomic_weight": 55.845, "period": 4, "group": 8, "electronegativity": 1.83},
    "Co": {"name": "코발트", "atomic_number": 27, "atomic_weight": 58.933, "period": 4, "group": 9, "electronegativity": 1.88},
    "Ni": {"name": "니켈", "atomic_number": 28, "atomic_weight": 58.693, "period": 4, "group": 10, "electronegativity": 1.91},
    "Cu": {"name": "구리", "atomic_number": 29, "atomic_weight": 63.546, "period": 4, "group": 11, "electronegativity": 1.9},
    "Zn": {"name": "아연", "atomic_number": 30, "atomic_weight": 65.38, "period": 4, "group": 12, "electronegativity": 1.65},
    "Ga": {"name": "갈륨", "atomic_number": 31, "atomic_weight": 69.723, "period": 4, "group": 13, "electronegativity": 1.81},
    "Ge": {"name": "저마늄", "atomic_number": 32, "atomic_weight": 72.630, "period": 4, "group": 14, "electronegativity": 2.01},
    "As": {"name": "비소", "atomic_number": 33, "atomic_weight": 74.922, "period": 4, "group": 15, "electronegativity": 2.18},
    "Se": {"name": "셀레늄", "atomic_number": 34, "atomic_weight": 78.971, "period": 4, "group": 16, "electronegativity": 2.55},
    "Br": {"name": "브로민", "atomic_number": 35, "atomic_weight": 79.904, "period": 4, "group": 17, "electronegativity": 2.96},
    "Kr": {"name": "크립톤", "atomic_number": 36, "atomic_weight": 83.798, "period": 4, "group": 18, "electronegativity": 3.0},
    "Rb": {"name": "루비듐", "atomic_number": 37, "atomic_weight": 85.468, "period": 5, "group": 1, "electronegativity": 0.82},
    "Sr": {"name": "스트론튬", "atomic_number": 38, "atomic_weight": 87.62, "period": 5, "group": 2, "electronegativity": 0.95},
    "Y": {"name": "이트륨", "atomic_number": 39, "atomic_weight": 88.905, "period": 5, "group": 3, "electronegativity": 1.22},
    "Zr": {"name": "지르코늄", "atomic_number": 40, "atomic_weight": 91.224, "period": 5, "group": 4, "electronegativity": 1.33},
    "Nb": {"name": "나이오븀", "atomic_number": 41, "atomic_weight": 92.906, "period": 5, "group": 5, "electronegativity": 1.6},
    "Mo": {"name": "몰리브데넘", "atomic_number": 42, "atomic_weight": 95.95, "period": 5, "group": 6, "electronegativity": 2.16},
    "Tc": {"name": "테크네튬", "atomic_number": 43, "atomic_weight": 98, "period": 5, "group": 7, "electronegativity": 1.9},
    "Ru": {"name": "루테늄", "atomic_number": 44, "atomic_weight": 101.07, "period": 5, "group": 8, "electronegativity": 2.2},
    "Rh": {"name": "로듐", "atomic_number": 45, "atomic_weight": 102.91, "period": 5, "group": 9, "electronegativity": 2.28},
    "Pd": {"name": "팔라듐", "atomic_number": 46, "atomic_weight": 106.42, "period": 5, "group": 10, "electronegativity": 2.2},
    "Ag": {"name": "은", "atomic_number": 47, "atomic_weight": 107.87, "period": 5, "group": 11, "electronegativity": 1.93},
    "Cd": {"name": "카드뮴", "atomic_number": 48, "atomic_weight": 112.41, "period": 5, "group": 12, "electronegativity": 1.69},
    "In": {"name": "인듐", "atomic_number": 49, "atomic_weight": 114.82, "period": 5, "group": 13, "electronegativity": 1.78},
    "Sn": {"name": "주석", "atomic_number": 50, "atomic_weight": 118.71, "period": 5, "group": 14, "electronegativity": 1.96},
    "Sb": {"name": "안티몬", "atomic_number": 51, "atomic_weight": 121.76, "period": 5, "group": 15, "electronegativity": 2.05},
    "Te": {"name": "텔루륨", "atomic_number": 52, "atomic_weight": 127.60, "period": 5, "group": 16, "electronegativity": 2.1},
    "I": {"name": "아이오딘", "atomic_number": 53, "atomic_weight": 126.90, "period": 5, "group": 17, "electronegativity": 2.66},
    "Xe": {"name": "크세논", "atomic_number": 54, "atomic_weight": 131.29, "period": 5, "group": 18, "electronegativity": 2.6},
    "Cs": {"name": "세슘", "atomic_number": 55, "atomic_weight": 132.91, "period": 6, "group": 1, "electronegativity": 0.79},
    "Ba": {"name": "바륨", "atomic_number": 56, "atomic_weight": 137.33, "period": 6, "group": 2, "electronegativity": 0.89},
    #란타넘족 따로 빼기 --------------------------------------------------------------------------------------------------------------
    "La": {"name": "란타넘", "atomic_number": 57, "atomic_weight": 138.91, "period": 10, "group": 1, "electronegativity": 1.1},
    "Ce": {"name": "세륨", "atomic_number": 58, "atomic_weight": 140.12, "period": 10, "group": 2, "electronegativity": 1.12},
    "Pr": {"name": "프라세오디뮴", "atomic_number": 59, "atomic_weight": 140.91, "period": 10, "group": 3, "electronegativity": 1.13},
    "Nd": {"name": "네오디뮴", "atomic_number": 60, "atomic_weight": 144.24, "period": 10, "group": 4 , "electronegativity": 1.14},
    "Pm": {"name": "프륨", "atomic_number": 61, "atomic_weight": 145, "period": 10, "group": 5, "electronegativity": 1.13},
    "Sm": {"name": "사마륨", "atomic_number": 62, "atomic_weight": 150.36, "period": 10, "group": 6, "electronegativity": 1.17},
    "Eu": {"name": "유로퓸", "atomic_number": 63, "atomic_weight": 151.98, "period": 10, "group": 7, "electronegativity": 1.2},
    "Gd": {"name": "가돌리늄", "atomic_number": 64, "atomic_weight": 157.25, "period": 10, "group": 8, "electronegativity": 1.2},
    "Tb": {"name": "터븀", "atomic_number": 65, "atomic_weight": 158.93, "period": 10, "group": 9, "electronegativity": 1.1},
    "Dy": {"name": "디스프로슘", "atomic_number": 66, "atomic_weight": 162.50, "period": 10, "group": 10, "electronegativity": 1.22},
    "Ho": {"name": "홀븀", "atomic_number": 67, "atomic_weight": 164.93, "period": 10, "group": 11, "electronegativity": 1.23},
    "Er": {"name": "에르븀", "atomic_number": 68, "atomic_weight": 167.26, "period": 10, "group": 12, "electronegativity": 1.24},
    "Tm": {"name": "툴륨", "atomic_number": 69, "atomic_weight": 168.93, "period": 10, "group": 13, "electronegativity": 1.25},
    "Yb": {"name": "이트븀", "atomic_number": 70, "atomic_weight": 173.04, "period": 10, "group": 14, "electronegativity": 1.1},
    "Lu": {"name": "루테튬", "atomic_number": 71, "atomic_weight": 175.00, "period": 10, "group": 15, "electronegativity": 1.27},
    #----------------------------------------------------------------------------------------------------------------------------------
    "Hf": {"name": "하프늄", "atomic_number": 72, "atomic_weight": 178.49, "period": 6, "group": 4, "electronegativity": 1.3},
    "Ta": {"name": "탄탈럼", "atomic_number": 73, "atomic_weight": 180.95, "period": 6, "group": 5, "electronegativity": 1.5},
    "W": {"name": "텅스텐", "atomic_number": 74, "atomic_weight": 183.84, "period": 6, "group": 6, "electronegativity": 2.36},
    "Re": {"name": "레늄", "atomic_number": 75, "atomic_weight": 186.21, "period": 6, "group": 7, "electronegativity": 1.9},
    "Os": {"name": "오스뮴", "atomic_number": 76, "atomic_weight": 190.23, "period": 6, "group": 8, "electronegativity": 2.2},
    "Ir": {"name": "이리듐", "atomic_number": 77, "atomic_weight": 192.217, "period": 6, "group": 9, "electronegativity": 2.2},
    "Pt": {"name": "백금", "atomic_number": 78, "atomic_weight": 195.084, "period": 6, "group": 10, "electronegativity": 2.28},
    "Au": {"name": "금", "atomic_number": 79, "atomic_weight": 196.967, "period": 6, "group": 11, "electronegativity": 2.54},
    "Hg": {"name": "수은", "atomic_number": 80, "atomic_weight": 200.592, "period": 6, "group": 12, "electronegativity": 2.0},
    "Tl": {"name": "탈륨", "atomic_number": 81, "atomic_weight": 204.38, "period": 6, "group": 13, "electronegativity": 1.62},
    "Pb": {"name": "납", "atomic_number": 82, "atomic_weight": 207.2, "period": 6, "group": 14, "electronegativity": 2.33},
    "Bi": {"name": "비스무트", "atomic_number": 83, "atomic_weight": 208.980, "period": 6, "group": 15, "electronegativity": 2.02},
    "Po": {"name": "폴로늄", "atomic_number": 84, "atomic_weight": 209, "period": 6, "group": 16, "electronegativity": 2.0},
    "At": {"name": "아스타틴", "atomic_number": 85, "atomic_weight": 210, "period": 6, "group": 17, "electronegativity": 2.2},
    "Rn": {"name": "라돈", "atomic_number": 86, "atomic_weight": 222, "period": 6, "group": 18, "electronegativity": None},
    "Fr": {"name": "프랑슘", "atomic_number": 87, "atomic_weight": 223, "period": 7, "group": 1, "electronegativity": 0.7},
    "Ra": {"name": "라듐", "atomic_number": 88, "atomic_weight": 226, "period": 7, "group": 2, "electronegativity": 0.9},
    #악티늄족 따로 빼기 ----------------------------------------------------------------------------------------------------
    "Ac": {"name": "악티늄", "atomic_number": 89, "atomic_weight": 227, "period": 11, "group": 1, "electronegativity": 1.1},
    "Th": {"name": "토륨", "atomic_number": 90, "atomic_weight": 232.037, "period": 11, "group": 2, "electronegativity": 1.3},
    "Pa": {"name": "프로트악티늄", "atomic_number": 91, "atomic_weight": 231.035, "period": 11, "group": 3, "electronegativity": 1.5},
    "U": {"name": "우라늄", "atomic_number": 92, "atomic_weight": 238.029, "period": 11, "group": 4, "electronegativity": 1.38},
    "Np": {"name": "넵투늄", "atomic_number": 93, "atomic_weight": 237, "period": 11, "group": 5, "electronegativity": 1.36},
    "Pu": {"name": "플루토늄", "atomic_number": 94, "atomic_weight": 244, "period": 11, "group": 6, "electronegativity": 1.28},
    "Am": {"name": "아메리슘", "atomic_number": 95, "atomic_weight": 243, "period": 11, "group": 7, "electronegativity": 1.13},
    "Cm": {"name": "퀴륨", "atomic_number": 96, "atomic_weight": 247, "period": 11, "group": 8, "electronegativity": 1.28},
    "Bk": {"name": "버클륨", "atomic_number": 97, "atomic_weight": 247, "period": 11, "group": 9, "electronegativity": 1.3},
    "Cf": {"name": "캘리포늄", "atomic_number": 98, "atomic_weight": 251, "period": 11, "group": 10, "electronegativity": 1.3},
    "Es": {"name": "아인슈타이늄", "atomic_number": 99, "atomic_weight": 252, "period": 11, "group": 11, "electronegativity": 1.3},
    "Fm": {"name": "페르뮴", "atomic_number": 100, "atomic_weight": 257, "period": 11, "group": 12, "electronegativity": 1.3},
    "Md": {"name": "멘델레븀", "atomic_number": 101, "atomic_weight": 258, "period": 11, "group": 13, "electronegativity": 1.3},
    "No": {"name": "노벨륨", "atomic_number": 102, "atomic_weight": 259, "period": 11, "group": 14, "electronegativity": 1.3},
    "Lr": {"name": "로렌슘", "atomic_number": 103, "atomic_weight": 262, "period": 11, "group": 15, "electronegativity": None},
    #---------------------------------------------------------------------------------------------------------------------------
    "Rf": {"name": "러더포듐", "atomic_number": 104, "atomic_weight": 267, "period": 7, "group": 4, "electronegativity": None},
    "Db": {"name": "더브늄", "atomic_number": 105, "atomic_weight": 270, "period": 7, "group": 5, "electronegativity": None},
    "Sg": {"name": "시보귬", "atomic_number": 106, "atomic_weight": 271, "period": 7, "group": 6, "electronegativity": None},
    "Bh": {"name": "보륨", "atomic_number": 107, "atomic_weight": 270, "period": 7, "group": 7, "electronegativity": None},
    "Hs": {"name": "하슘", "atomic_number": 108, "atomic_weight": 277, "period": 7, "group": 8, "electronegativity": None},
    "Mt": {"name": "마이트너륨", "atomic_number": 109, "atomic_weight": 278, "period": 7, "group": 9, "electronegativity": None},
    "Ds": {"name": "다름슈타튬", "atomic_number": 110, "atomic_weight": 281, "period": 7, "group": 10, "electronegativity": None},
    "Rg": {"name": "렌트게늄", "atomic_number": 111, "atomic_weight": 282, "period": 7, "group": 11, "electronegativity": None},
    "Cn": {"name": "코페르니슘", "atomic_number": 112, "atomic_weight": 285, "period": 7, "group": 12, "electronegativity": None},
    "Nh": {"name": "니호늄", "atomic_number": 113, "atomic_weight": 286, "period": 7, "group": 13, "electronegativity": None},
    "Fl": {"name": "플레로븀", "atomic_number": 114, "atomic_weight": 289, "period": 7, "group": 14, "electronegativity": None},
    "Mc": {"name": "모스코븀", "atomic_number": 115, "atomic_weight": 290, "period": 7, "group": 15, "electronegativity": None},
    "Lv": {"name": "리버모륨", "atomic_number": 116, "atomic_weight": 293, "period": 7, "group": 16, "electronegativity": None},
    "Ts": {"name": "테네신", "atomic_number": 117, "atomic_weight": 294, "period": 7, "group": 17, "electronegativity": None},
    "Og": {"name": "오가네손", "atomic_number": 118, "atomic_weight": 294, "period": 7, "group": 18, "electronegativity": None}
} 
@app.route('/')
def index():
    return render_template('index.html', elements=elements)

@app.route('/get_element', methods=['POST'])
def get_element():
    symbol = request.form.get('symbol')
    element_data = elements.get(symbol, {})
    return jsonify(element_data)

if __name__ == '__main__':
    app.run(debug=True)
